apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  labels:
    app: java
  name: java
  namespace: java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java
  serviceName: java
  template:
    metadata:
      labels:
        app: java
    spec:
      containers:
        - image: 'docker-registry.default.svc:5000/java/java:latest'
          imagePullPolicy: Always
          name: java
          command: ["/bin/sh", "-ec", "while :; do echo '.'; sleep 5 ; done"]
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
